from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

from workflow_harnesses.fractal_kit_pipeline.stage_contracts import stage_contracts


def build_stage_ledger(
    run_dir: Path,
    target_count: int,
    expansion_points: List[Dict[str, Any]],
    expansion_report: Dict[str, Any],
    first_stage_breadth_audit: Dict[str, Any],
    reveal_records: List[Dict[str, Any]],
    revealed_reduced_audit: Dict[str, Any],
    idea_records: List[Dict[str, Any]],
    idea_matrix_audit: Dict[str, Any],
    filtered_records: List[Dict[str, Any]],
    atomic_filter_audit: Dict[str, Any],
    filter_report: Dict[str, Any],
    domain_merge_report: Dict[str, Any],
    domain_merge_input_audit: Dict[str, Any],
    canonicalized_records: List[Dict[str, Any]],
    canonicalization_report: Dict[str, Any],
    domain_canonicalization_audit: Dict[str, Any],
    merge_report: Dict[str, Any],
    kit_canonicalized_records: List[Dict[str, Any]],
    kit_canonicalization_report: Dict[str, Any],
    final_quality_report: Dict[str, Any],
    source_shape_audit: Dict[str, Any],
    diversity_audit: Dict[str, Any],
    dependency_graph_audit: Dict[str, Any],
    build_batch_manifest: Dict[str, Any],
    build_batch_replay_smoke: Dict[str, Any],
    build_work_orders_report: Dict[str, Any],
    build_batch_packets_report: Dict[str, Any],
    build_batch_dry_run_report: Dict[str, Any],
    build_promotion_index: Dict[str, Any],
    promoted_batches_report: Dict[str, Any],
    downstream_build_chain_integrity: Dict[str, Any],
    final_bucket_reconciliation: Dict[str, Any],
    feed_forward_artifact_integrity: Dict[str, Any],
    stage_contract_integrity: Dict[str, Any],
    final_lineage_integrity: Dict[str, Any],
    merge_review_coverage: Dict[str, Any],
    prompt_control_indirection: Dict[str, Any],
    stage_resume_plan: Dict[str, Any],
    artifact_schema_index: Dict[str, Any],
    handoff_manifest: Dict[str, Any],
    slot_decision_report: Dict[str, Any],
    simulator_report: Dict[str, Any],
    slot_decision_trace_integrity: Dict[str, Any],
    final_records: List[Dict[str, Any]],
    final_bucket_run_dir: str,
    line_count: int,
    malformed: int,
    duplicate_ids: int,
    bucket_report: Dict[str, Any],
    failed_ingests: List[Dict[str, Any]],
) -> Dict[str, Any]:
    contracts = {contract["name"]: contract for contract in stage_contracts()}
    stages = [
        _stage(
            contracts,
            "research-pack",
            run_dir,
            ["research-pack.json"],
            {"artifacts": 1},
            _exists(run_dir, "research-pack.json"),
            "Resume from setup stage if missing.",
        ),
        _stage(
            contracts,
            "expansion-points",
            run_dir,
            ["expansion-points.jsonl", "expansion-report.json"],
            {
                "raw_generations": expansion_report.get("raw_generations", 0),
                "candidate_count": expansion_report.get("candidate_count", 0),
                "accepted_count": len(expansion_points),
                "rejected_count": expansion_report.get("rejected_count", 0),
            },
            len(expansion_points) > 0 and _exists(run_dir, "expansion-points.jsonl", "expansion-report.json"),
            "Resume at reveal/reduce using expansion-points.jsonl.",
        ),
        _stage(
            contracts,
            "first-stage-breadth-audit",
            run_dir,
            ["first-stage-breadth-audit.json"],
            {
                "accepted_count": first_stage_breadth_audit.get("accepted_count", 0),
                "candidate_count": first_stage_breadth_audit.get("candidate_count", 0),
                "rejected_count": first_stage_breadth_audit.get("rejected_count", 0),
                "acceptance_ratio": first_stage_breadth_audit.get("acceptance_ratio", 0),
                "failed_checks": len(first_stage_breadth_audit.get("failed", [])),
            },
            bool(first_stage_breadth_audit.get("ok")) and _exists(run_dir, "first-stage-breadth-audit.json"),
            "Repair first-stage prompt stance or rejection policy, then rerun breadth audit.",
        ),
        _stage(
            contracts,
            "revealed-reduced",
            run_dir,
            ["revealed-reduced.jsonl"],
            {"records": len(reveal_records)},
            len(reveal_records) > 0 and _exists(run_dir, "revealed-reduced.jsonl"),
            "Resume at idea matrix using revealed-reduced.jsonl.",
        ),
        _stage(
            contracts,
            "revealed-reduced-audit",
            run_dir,
            ["revealed-reduced-audit.json"],
            {
                "expansion_points": revealed_reduced_audit.get("expansion_points", 0),
                "reveal_records": revealed_reduced_audit.get("reveal_records", 0),
                "unique_reduced": revealed_reduced_audit.get("unique_reduced", 0),
                "generic_reduced": revealed_reduced_audit.get("generic_reduced", 0),
                "failed_checks": len(revealed_reduced_audit.get("failed", [])),
            },
            bool(revealed_reduced_audit.get("ok")) and _exists(run_dir, "revealed-reduced-audit.json"),
            "Repair reveal/reduce feed-forward quality, then rerun revealed-reduced audit.",
        ),
        _stage(
            contracts,
            "idea-matrix",
            run_dir,
            ["idea-matrix.jsonl"],
            {
                "records": len(idea_records),
                "raw_count": filter_report.get("raw_count", 0),
                "target_with_buffer": target_count + max(512, target_count // 10),
            },
            len(idea_records) >= target_count
            and filter_report.get("raw_count", 0) == len(idea_records)
            and _exists(run_dir, "idea-matrix.jsonl"),
            "Resume at atomic/idempotent filter from idea-matrix.jsonl.",
        ),
        _stage(
            contracts,
            "idea-matrix-audit",
            run_dir,
            ["idea-matrix-audit.json"],
            {
                "record_count": idea_matrix_audit.get("record_count", 0),
                "unique_semantic_keys": idea_matrix_audit.get("unique_semantic_keys", 0),
                "unique_domains": idea_matrix_audit.get("unique_domains", 0),
                "unique_reveal_signals": idea_matrix_audit.get("unique_reveal_signals", 0),
                "failed_checks": len(idea_matrix_audit.get("failed", [])),
            },
            bool(idea_matrix_audit.get("ok")) and _exists(run_dir, "idea-matrix-audit.json"),
            "Repair deterministic matrix expansion, then rerun idea-matrix audit.",
        ),
        _stage(
            contracts,
            "atomic-idempotent-filter",
            run_dir,
            ["filtered-candidates.jsonl", "filter-report.json"],
            {
                "raw_count": filter_report.get("raw_count", 0),
                "records": len(filtered_records),
                "kept_count": filter_report.get("kept_count", 0),
                "rejected_count": filter_report.get("rejected_count", 0),
            },
            len(filtered_records) >= target_count
            and filter_report.get("kept_count", 0) == len(filtered_records)
            and _exists(run_dir, "filtered-candidates.jsonl", "filter-report.json"),
            "Resume at domain merge review from filtered-candidates.jsonl.",
        ),
        _stage(
            contracts,
            "atomic-filter-audit",
            run_dir,
            ["atomic-filter-audit.json"],
            {
                "matrix_records": atomic_filter_audit.get("matrix_records", 0),
                "filtered_records": atomic_filter_audit.get("filtered_records", 0),
                "unique_semantic_keys": atomic_filter_audit.get("unique_semantic_keys", 0),
                "rejected_count": atomic_filter_audit.get("rejected_count", 0),
                "failed_checks": len(atomic_filter_audit.get("failed", [])),
            },
            bool(atomic_filter_audit.get("ok")) and _exists(run_dir, "atomic-filter-audit.json"),
            "Repair atomic/idempotent filtering, then rerun atomic filter audit.",
        ),
        _stage(
            contracts,
            "recursive-domain-merge-review",
            run_dir,
            ["domain-merge-report.json"],
            {
                "domain_count": domain_merge_report.get("domain_count", 0),
                "canonical_group_count": domain_merge_report.get("canonical_group_count", 0),
                "pairs_reviewed": domain_merge_report.get("pairs_reviewed", 0),
                "same_pairs": domain_merge_report.get("same_pairs", 0),
            },
            domain_merge_report.get("pairs_reviewed", 0) >= 0 and _exists(run_dir, "domain-merge-report.json"),
            "Resume at domain canonicalization with domain-merge-report.json.",
        ),
        _stage(
            contracts,
            "domain-merge-input-audit",
            run_dir,
            ["domain-merge-input-audit.json"],
            {
                "filtered_records": domain_merge_input_audit.get("filtered_records", 0),
                "unique_domains": domain_merge_input_audit.get("unique_domains", 0),
                "unique_parent_domains": domain_merge_input_audit.get("unique_parent_domains", 0),
                "pairs_reviewed": domain_merge_input_audit.get("pairs_reviewed", 0),
                "failed_checks": len(domain_merge_input_audit.get("failed", [])),
            },
            bool(domain_merge_input_audit.get("ok")) and _exists(run_dir, "domain-merge-input-audit.json"),
            "Repair filtered candidate domain fields or merge review report, then rerun domain merge input audit.",
        ),
        _stage(
            contracts,
            "domain-canonicalization",
            run_dir,
            ["domain-canonicalized.jsonl", "domain-canonicalization-report.json"],
            {
                "input_records": canonicalization_report.get("input_records", 0),
                "output_records": len(canonicalized_records),
                "canonical_groups": canonicalization_report.get("canonical_groups", 0),
            },
            bool(canonicalization_report.get("ok"))
            and _exists(run_dir, "domain-canonicalized.jsonl", "domain-canonicalization-report.json"),
            "Resume at kit merge review with domain-canonicalized.jsonl.",
        ),
        _stage(
            contracts,
            "domain-canonicalization-audit",
            run_dir,
            ["domain-canonicalization-audit.json"],
            {
                "filtered_records": domain_canonicalization_audit.get("filtered_records", 0),
                "canonicalized_records": domain_canonicalization_audit.get("canonicalized_records", 0),
                "canonicalized_count": domain_canonicalization_audit.get("canonicalized_count", 0),
                "preserved_count": domain_canonicalization_audit.get("preserved_count", 0),
                "failed_checks": len(domain_canonicalization_audit.get("failed", [])),
            },
            bool(domain_canonicalization_audit.get("ok"))
            and _exists(run_dir, "domain-canonicalization-audit.json"),
            "Repair canonical domain metadata or source evidence before kit merge review.",
        ),
        _stage(
            contracts,
            "recursive-kit-merge-review",
            run_dir,
            ["merge-review-report.json"],
            {
                "pairs_reviewed": merge_report.get("pairs_reviewed", 0),
                "same_pairs": merge_report.get("same_pairs", 0),
            },
            merge_report.get("pairs_reviewed", 0) >= 0 and _exists(run_dir, "merge-review-report.json"),
            "Resume at kit canonicalization with merge-review-report.json.",
        ),
        _stage(
            contracts,
            "kit-canonicalization",
            run_dir,
            ["kit-canonicalized.jsonl", "kit-canonicalization-report.json"],
            {
                "input_records": kit_canonicalization_report.get("input_records", 0),
                "output_records": len(kit_canonicalized_records),
                "canonical_groups": kit_canonicalization_report.get("canonical_groups", 0),
            },
            bool(kit_canonicalization_report.get("ok"))
            and _exists(run_dir, "kit-canonicalized.jsonl", "kit-canonicalization-report.json"),
            "Resume at final selection with kit-canonicalized.jsonl.",
        ),
        _stage(
            contracts,
            "final-selection",
            run_dir,
            ["selected-final-records.jsonl"],
            {"selected_records": len(final_records), "target_count": target_count},
            len(final_records) == target_count and _exists(run_dir, "selected-final-records.jsonl"),
            "Resume at final quality gate or final output with selected records.",
        ),
        _stage(
            contracts,
            "final-quality-gate",
            run_dir,
            ["final-quality-report.json"],
            {
                "kept_records": final_quality_report.get("kept_records", 0),
                "rejected_records": final_quality_report.get("rejected_records", 0),
                "unique_record_ids": final_quality_report.get("unique_record_ids", 0),
                "unique_semantic_keys": final_quality_report.get("unique_semantic_keys", 0),
            },
            bool(final_quality_report.get("ok")) and _exists(run_dir, "final-quality-report.json"),
            "Fix final record shape or canonical metadata, then rerun final quality gate.",
        ),
        _stage(
            contracts,
            "source-shape-audit",
            run_dir,
            ["source-shape-audit.json"],
            {
                "records_checked": source_shape_audit.get("records_checked", 0),
                "record_failure_count": source_shape_audit.get("record_failure_count", 0),
                "missing_slots": source_shape_audit.get("missing_slots", 0),
                "renderer_owned": source_shape_audit.get("renderer_owned", 0),
                "promotion_gaps": source_shape_audit.get("promotion_gaps", 0),
            },
            bool(source_shape_audit.get("ok")) and _exists(run_dir, "source-shape-audit.json"),
            "Repair source-shape slot coverage or research-pack evidence, then rerun source-shape audit.",
        ),
        _stage(
            contracts,
            "diversity-audit",
            run_dir,
            ["diversity-audit.json"],
            {
                "unique_canonical_domains": diversity_audit.get("unique_canonical_domains", 0),
                "unique_categories": diversity_audit.get("unique_categories", 0),
                "unique_signatures": diversity_audit.get("unique_signatures", 0),
                "max_duplicate_signature_count": diversity_audit.get("max_duplicate_signature_count", 0),
            },
            bool(diversity_audit.get("ok")) and _exists(run_dir, "diversity-audit.json"),
            "Improve expansion/reduce matrix breadth, then rerun diversity audit.",
        ),
        _stage(
            contracts,
            "dependency-graph-audit",
            run_dir,
            ["dependency-graph-audit.json"],
            {
                "unique_required_tokens": dependency_graph_audit.get("unique_required_tokens", 0),
                "unique_provided_tokens": dependency_graph_audit.get("unique_provided_tokens", 0),
                "unique_primary_dependencies": dependency_graph_audit.get("unique_primary_dependencies", 0),
                "direct_self_edges": dependency_graph_audit.get("direct_self_edges", 0),
                "malformed_tokens": dependency_graph_audit.get("malformed_tokens", 0),
            },
            bool(dependency_graph_audit.get("ok")) and _exists(run_dir, "dependency-graph-audit.json"),
            "Repair requires/provides mapping, then rerun dependency graph audit.",
        ),
        _stage(
            contracts,
            "build-batch-manifest",
            run_dir,
            ["build-batches.json"],
            {
                "batch_count": build_batch_manifest.get("batch_count", 0),
                "group_count": build_batch_manifest.get("group_count", 0),
                "record_count": build_batch_manifest.get("record_count", 0),
                "max_batch_size": build_batch_manifest.get("max_batch_size", 0),
            },
            bool(build_batch_manifest.get("ok")) and _exists(run_dir, "build-batches.json"),
            "Regenerate build-batches.json from final-kits.jsonl.",
        ),
        _stage(
            contracts,
            "build-batch-replay-smoke",
            run_dir,
            ["build-batch-replay-smoke.json"],
            {
                "batches_replayed": build_batch_replay_smoke.get("batches_replayed", 0),
                "records_replayed": build_batch_replay_smoke.get("records_replayed", 0),
                "failed_batch_count": build_batch_replay_smoke.get("failed_batch_count", 0),
            },
            bool(build_batch_replay_smoke.get("ok")) and _exists(run_dir, "build-batch-replay-smoke.json"),
            "Repair build-batches.json or final-kits.jsonl, then rerun batch replay smoke.",
        ),
        _stage(
            contracts,
            "build-work-orders",
            run_dir,
            ["build-work-orders.jsonl", "build-work-orders-report.json"],
            {
                "work_order_count": build_work_orders_report.get("work_order_count", 0),
                "batch_count": build_work_orders_report.get("batch_count", 0),
                "assigned_records": build_work_orders_report.get("assigned_records", 0),
            },
            bool(build_work_orders_report.get("ok"))
            and _exists(run_dir, "build-work-orders.jsonl", "build-work-orders-report.json"),
            "Regenerate build work orders from build-batches.json.",
        ),
        _stage(
            contracts,
            "build-batch-packets",
            run_dir,
            ["build-inputs/index.json", "build-batch-packets-report.json"],
            {
                "packet_count": build_batch_packets_report.get("packet_count", 0),
                "work_order_count": build_batch_packets_report.get("work_order_count", 0),
                "packet_records": build_batch_packets_report.get("packet_records", 0),
                "missing_record_refs": len(build_batch_packets_report.get("missing_record_refs", [])),
            },
            bool(build_batch_packets_report.get("ok"))
            and _exists(run_dir, "build-inputs/index.json", "build-batch-packets-report.json"),
            "Regenerate build input packets from build-work-orders.jsonl and final-kits.jsonl.",
        ),
        _stage(
            contracts,
            "build-batch-dry-run",
            run_dir,
            ["batch-results/index.json", "build-batch-dry-run-report.json"],
            {
                "batch_count": build_batch_dry_run_report.get("batch_count", 0),
                "packet_count": build_batch_dry_run_report.get("packet_count", 0),
                "records_checked": build_batch_dry_run_report.get("records_checked", 0),
                "failed_batch_count": build_batch_dry_run_report.get("failed_batch_count", 0),
            },
            bool(build_batch_dry_run_report.get("ok"))
            and _exists(run_dir, "batch-results/index.json", "build-batch-dry-run-report.json"),
            "Regenerate dry-run build results from materialized build input packets.",
        ),
        _stage(
            contracts,
            "build-promotion-index",
            run_dir,
            ["build-promotion-index.json"],
            {
                "ready_count": build_promotion_index.get("ready_count", 0),
                "blocked_count": build_promotion_index.get("blocked_count", 0),
                "record_count": build_promotion_index.get("record_count", 0),
            },
            bool(build_promotion_index.get("ok")) and _exists(run_dir, "build-promotion-index.json"),
            "Resume downstream promotion from build-promotion-index.json.",
        ),
        _stage(
            contracts,
            "promoted-batches",
            run_dir,
            ["promoted-batches/index.json", "promoted-batches-report.json"],
            {
                "promoted_count": promoted_batches_report.get("promoted_count", 0),
                "blocked_count": promoted_batches_report.get("blocked_count", 0),
                "record_count": promoted_batches_report.get("record_count", 0),
            },
            bool(promoted_batches_report.get("ok"))
            and _exists(run_dir, "promoted-batches/index.json", "promoted-batches-report.json"),
            "Resume external build implementation from promoted-batches/index.json.",
        ),
        _stage(
            contracts,
            "downstream-build-chain-integrity",
            run_dir,
            ["downstream-build-chain-integrity.json"],
            {
                "final_records": downstream_build_chain_integrity.get("counts", {}).get("final_records", 0),
                "build_batches": downstream_build_chain_integrity.get("counts", {}).get("build_batches", 0),
                "work_orders": downstream_build_chain_integrity.get("counts", {}).get("work_orders", 0),
                "packets": downstream_build_chain_integrity.get("counts", {}).get("packets", 0),
                "batch_results": downstream_build_chain_integrity.get("counts", {}).get("batch_results", 0),
                "promoted_records": downstream_build_chain_integrity.get("counts", {}).get("promoted_records", 0),
                "failed_checks": len(downstream_build_chain_integrity.get("failed", [])),
            },
            bool(downstream_build_chain_integrity.get("ok"))
            and _exists(run_dir, "downstream-build-chain-integrity.json"),
            "Repair downstream batch handoff artifacts, then rerun build-chain integrity.",
        ),
        _stage(
            contracts,
            "final-bucket-reconciliation",
            run_dir,
            ["final-bucket-reconciliation.json"],
            {
                "final_records": final_bucket_reconciliation.get("final_records", 0),
                "bucket_records": final_bucket_reconciliation.get("bucket_records", 0),
                "missing_from_bucket": final_bucket_reconciliation.get("missing_from_bucket", 0),
                "extra_in_bucket": final_bucket_reconciliation.get("extra_in_bucket", 0),
                "bucket_duplicate_ids": final_bucket_reconciliation.get("bucket_duplicate_ids", 0),
            },
            bool(final_bucket_reconciliation.get("ok")) and _exists(run_dir, "final-bucket-reconciliation.json"),
            "Re-run final bucket ingestion if bucket ids do not exactly match final-kits.jsonl.",
        ),
        _stage(
            contracts,
            "feed-forward-artifact-integrity",
            run_dir,
            ["feed-forward-artifact-integrity.json"],
            {
                "artifact_count": feed_forward_artifact_integrity.get("artifact_count", 0),
                "failed_checks": len(feed_forward_artifact_integrity.get("failed", [])),
                "target_count": feed_forward_artifact_integrity.get("target_count", 0),
            },
            bool(feed_forward_artifact_integrity.get("ok"))
            and _exists(run_dir, "feed-forward-artifact-integrity.json"),
            "Repair missing or malformed stage artifacts, then rerun artifact integrity.",
        ),
        _stage(
            contracts,
            "stage-contract-integrity",
            run_dir,
            ["stage-contract-integrity.json"],
            {
                "contract_count": stage_contract_integrity.get("contract_count", 0),
                "manifest_stage_count": stage_contract_integrity.get("manifest_stage_count", 0),
                "artifact_stage_count": stage_contract_integrity.get("artifact_stage_count", 0),
                "failed_checks": len(stage_contract_integrity.get("failed", [])),
            },
            bool(stage_contract_integrity.get("ok")) and _exists(run_dir, "stage-contract-integrity.json"),
            "Repair manifest/stage-contract drift, then rerun stage contract integrity.",
        ),
        _stage(
            contracts,
            "final-lineage-integrity",
            run_dir,
            ["final-lineage-integrity.json"],
            {
                "final_count": final_lineage_integrity.get("counts", {}).get("final", 0),
                "selected_final_count": final_lineage_integrity.get("counts", {}).get("selected_final", 0),
                "canonical_kit_refs": final_lineage_integrity.get("counts", {}).get("canonical_kit_refs", 0),
                "kit_alias_refs": final_lineage_integrity.get("counts", {}).get("kit_alias_refs", 0),
                "domain_evidence_refs": final_lineage_integrity.get("counts", {}).get("domain_evidence_refs", 0),
                "failed_checks": len(final_lineage_integrity.get("failed", [])),
            },
            bool(final_lineage_integrity.get("ok")) and _exists(run_dir, "final-lineage-integrity.json"),
            "Repair broken feed-forward ids or canonical references, then rerun final lineage integrity.",
        ),
        _stage(
            contracts,
            "merge-review-coverage",
            run_dir,
            ["merge-review-coverage.json"],
            {
                "domain_pairs_reviewed": merge_review_coverage.get("counts", {}).get("domain_pairs_reviewed", 0),
                "domain_depths": merge_review_coverage.get("counts", {}).get("domain_depths", []),
                "kit_pairs_reviewed": merge_review_coverage.get("counts", {}).get("kit_pairs_reviewed", 0),
                "kit_depths": merge_review_coverage.get("counts", {}).get("kit_depths", []),
                "final_records_checked": merge_review_coverage.get("counts", {}).get("final_records_checked", 0),
                "failed_checks": len(merge_review_coverage.get("failed", [])),
            },
            bool(merge_review_coverage.get("ok")) and _exists(run_dir, "merge-review-coverage.json"),
            "Repair merge review outputs or canonical metadata, then rerun merge review coverage.",
        ),
        _stage(
            contracts,
            "prompt-control-indirection",
            run_dir,
            ["prompt-control-indirection.json"],
            {
                "prompt_count": prompt_control_indirection.get("prompt_count", 0),
                "forbidden_terms": prompt_control_indirection.get("forbidden_terms", []),
                "failed_checks": len(prompt_control_indirection.get("failed", [])),
            },
            bool(prompt_control_indirection.get("ok")) and _exists(run_dir, "prompt-control-indirection.json"),
            "Repair direct target leakage or provider controls, then rerun prompt/control indirection audit.",
        ),
        _stage(
            contracts,
            "slot-decision-trace-integrity",
            run_dir,
            ["slot-decision-trace-integrity.json"],
            {
                "sampled_records": slot_decision_trace_integrity.get("counts", {}).get("sampled_records", 0),
                "decision_records": slot_decision_trace_integrity.get("counts", {}).get("decision_records", 0),
                "required_slots": slot_decision_trace_integrity.get("counts", {}).get("required_slots", 0),
                "decision_nodes": slot_decision_trace_integrity.get("counts", {}).get("decision_nodes", 0),
                "failed_checks": len(slot_decision_trace_integrity.get("failed", [])),
            },
            bool(slot_decision_trace_integrity.get("ok")) and _exists(run_dir, "slot-decision-trace-integrity.json"),
            "Repair LFM slot decision traces or simulator slot sample, then rerun trace integrity.",
        ),
        _stage(
            contracts,
            "stage-resume-plan",
            run_dir,
            ["stage-resume-plan.json"],
            {
                "stage_count": stage_resume_plan.get("stage_count", 0),
                "deferred_count": len(stage_resume_plan.get("deferred_while_building", [])),
                "failed_checks": len(stage_resume_plan.get("failed", [])),
            },
            bool(stage_resume_plan.get("ok")) and _exists(run_dir, "stage-resume-plan.json"),
            "Use stage-resume-plan.json to resume from the nearest complete artifact boundary.",
        ),
        _stage(
            contracts,
            "artifact-schema-index",
            run_dir,
            ["artifact-schema-index.json"],
            {
                "jsonl_artifacts": artifact_schema_index.get("jsonl_artifact_count", 0),
                "json_artifacts": artifact_schema_index.get("json_artifact_count", 0),
                "sample_limit": artifact_schema_index.get("sample_limit", 0),
                "failed_checks": len(artifact_schema_index.get("failed", [])),
            },
            bool(artifact_schema_index.get("ok")) and _exists(run_dir, "artifact-schema-index.json"),
            "Use artifact-schema-index.json before parsing stage artifacts in downstream tools.",
        ),
        _stage(
            contracts,
            "handoff-manifest",
            run_dir,
            ["handoff-manifest.json"],
            {
                "target_count": handoff_manifest.get("target_count", 0),
                "artifact_count": len(handoff_manifest.get("artifact_map", {})),
                "failed_checks": len(handoff_manifest.get("failed", [])),
            },
            bool(handoff_manifest.get("ok")) and _exists(run_dir, "handoff-manifest.json"),
            "Start future work from handoff-manifest.json.",
        ),
        _stage(
            contracts,
            "lfm-slot-decision-tree",
            run_dir,
            ["lfm-slot-decisions.json"],
            {
                "records_requested": slot_decision_report.get("records_requested", 0),
                "records_tested": slot_decision_report.get("records_tested", 0),
                "records_accepted": slot_decision_report.get("records_accepted", 0),
                "records_rejected": slot_decision_report.get("records_rejected", 0),
            },
            bool(slot_decision_report.get("ok")) and _exists(run_dir, "lfm-slot-decisions.json"),
            "Rerun low-temperature slot decision tree on final records.",
        ),
        _stage(
            contracts,
            "simulator-slot-smoke",
            run_dir,
            ["simulator-slot-smoke.json"],
            {
                "records_tested": simulator_report.get("records_tested", 0),
                "accepted": simulator_report.get("accepted", 0),
                "rejected": simulator_report.get("rejected", 0),
            },
            bool(simulator_report.get("ok")) and _exists(run_dir, "simulator-slot-smoke.json"),
            "Rerun simplified simulator smoke on final records.",
        ),
        _stage(
            contracts,
            "final-output",
            run_dir,
            ["final-kits.jsonl", "stage-ledger.json", "report.json", "report.md"],
            {
                "final_jsonl_lines": line_count,
                "final_jsonl_malformed": malformed,
                "duplicate_record_ids": duplicate_ids,
                "bucket_total_records": bucket_report.get("total_records", 0),
                "failed_ingests": len(failed_ingests),
            },
            line_count == target_count
            and malformed == 0
            and duplicate_ids == 0
            and bucket_report.get("ok")
            and bucket_report.get("total_records") == target_count
            and not failed_ingests
            and _exists(run_dir, "final-kits.jsonl"),
            "Rerun final output ingestion and report assembly.",
            extra={"final_bucket_run_dir": final_bucket_run_dir},
        ),
    ]
    missing_contracts = sorted(set(contracts) - {stage["name"] for stage in stages})
    return {
        "ok": all(stage["gate_ok"] for stage in stages) and not missing_contracts,
        "stage_count": len(stages),
        "contract_count": len(contracts),
        "missing_contracts": missing_contracts,
        "stages": stages,
    }


def _stage(
    contracts: Dict[str, Dict[str, Any]],
    name: str,
    run_dir: Path,
    artifacts: List[str],
    counts: Dict[str, Any],
    gate_ok: bool,
    resume_hint: str,
    extra: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    contract = contracts[name]
    entry = {
        "name": name,
        "input": contract["input"],
        "output": contract["output"],
        "purpose": contract["purpose"],
        "gate": contract["gate"],
        "artifacts": [_artifact(run_dir, artifact) for artifact in artifacts],
        "counts": counts,
        "gate_ok": bool(gate_ok),
        "resume_hint": resume_hint,
    }
    if extra:
        entry.update(extra)
    return entry


def _artifact(run_dir: Path, relative_path: str) -> Dict[str, Any]:
    path = run_dir / relative_path
    return {
        "path": str(path),
        "relative_path": relative_path,
        "exists": path.exists(),
        "bytes": path.stat().st_size if path.exists() else 0,
    }


def _exists(run_dir: Path, *relative_paths: str) -> bool:
    return all((run_dir / relative_path).exists() for relative_path in relative_paths)
