from __future__ import annotations

from typing import Any, Dict, List


def stage_contracts() -> List[Dict[str, Any]]:
    return [
        {
            "name": "research-pack",
            "input": "local Nexus/ProtoKit source notes",
            "output": "research-pack.json",
            "purpose": "record reviewed kit-shape evidence without adding it to generation prompts",
            "gate": "artifact exists",
        },
        {
            "name": "expansion-points",
            "input": "LIST GOAL plus base signal triplets",
            "output": "expansion-points.jsonl, expansion-report.json",
            "purpose": "generate broad expansion points while rejecting only obvious waste",
            "gate": "non-empty, exact-unique, permissive relevance Y/N",
        },
        {
            "name": "first-stage-breadth-audit",
            "input": "expansion-points.jsonl plus expansion-report.json",
            "output": "first-stage-breadth-audit.json",
            "purpose": "prove first-stage expansion remains broad and defers semantic cleanup",
            "gate": "prompt stance, rejection reasons, exact uniqueness, and acceptance breadth pass",
        },
        {
            "name": "revealed-reduced",
            "input": "expansion-points.jsonl",
            "output": "revealed-reduced.jsonl",
            "purpose": "ask what information a point reveals, then reduce it to a reusable capability phrase",
            "gate": "short revealed and reduced phrases with fallback for generic filler",
        },
        {
            "name": "revealed-reduced-audit",
            "input": "expansion-points.jsonl plus revealed-reduced.jsonl",
            "output": "revealed-reduced-audit.json",
            "purpose": "prove expansion evidence fed forward into compact reusable reduced capability phrases",
            "gate": "one-to-one coverage, non-empty compact phrases, no generic filler, and enough reduced breadth",
        },
        {
            "name": "idea-matrix",
            "input": "revealed-reduced.jsonl",
            "output": "idea-matrix.jsonl",
            "purpose": "deterministically expand reduced capability phrases into kit-shaped candidates",
            "gate": "target count plus buffer generated and persisted",
        },
        {
            "name": "idea-matrix-audit",
            "input": "idea-matrix.jsonl plus revealed-reduced.jsonl",
            "output": "idea-matrix-audit.json",
            "purpose": "prove matrix expansion preserves reduced evidence and produces broad unique candidate records",
            "gate": "target buffer, required payload fields, semantic uniqueness, reveal signal coverage, and domain breadth pass",
        },
        {
            "name": "atomic-idempotent-filter",
            "input": "idea-matrix.jsonl",
            "output": "filtered-candidates.jsonl, filter-report.json",
            "purpose": "keep atomic, idempotent, semantic-key-unique candidates",
            "gate": "atomic true, idempotent true, unique semantic key, persisted filtered output",
        },
        {
            "name": "atomic-filter-audit",
            "input": "idea-matrix.jsonl plus filtered-candidates.jsonl plus filter-report.json",
            "output": "atomic-filter-audit.json",
            "purpose": "prove filtered records are a faithful atomic/idempotent semantic-unique subset of the matrix",
            "gate": "count accounting, matrix subset, target preservation, semantic uniqueness, and filter contract pass",
        },
        {
            "name": "recursive-domain-merge-review",
            "input": "filtered-candidates.jsonl",
            "output": "domain-merge-report.json",
            "purpose": "review similar domain paths through recursive low-temperature Y/N gates",
            "gate": "merge only reviewer-approved same-domain pairs",
        },
        {
            "name": "domain-merge-input-audit",
            "input": "filtered-candidates.jsonl plus domain-merge-report.json",
            "output": "domain-merge-input-audit.json",
            "purpose": "prove filtered broad candidates form valid domain-index input for recursive merge review",
            "gate": "target-sized records, namespaced domains, broad parent/category coverage, clean Y/N reviews",
        },
        {
            "name": "domain-canonicalization",
            "input": "filtered candidate records plus domain-merge-report.json",
            "output": "domain-canonicalized.jsonl, domain-canonicalization-report.json",
            "purpose": "apply reviewed canonical domain groups to every candidate while preserving aliases and evidence",
            "gate": "output count equals input count",
        },
        {
            "name": "domain-canonicalization-audit",
            "input": "filtered-candidates.jsonl plus domain-canonicalized.jsonl plus domain merge artifacts",
            "output": "domain-canonicalization-audit.json",
            "purpose": "prove reviewed canonical domain metadata was applied without losing source payload or evidence",
            "gate": "record ids, canonical fields, aliases, source evidence, and report counts align",
        },
        {
            "name": "recursive-kit-merge-review",
            "input": "domain-canonicalized records",
            "output": "merge-review-report.json",
            "purpose": "review same atomic reusable capability through needs/dependencies Y/N gates",
            "gate": "merge only reviewer-approved same-kit pairs",
        },
        {
            "name": "kit-canonicalization",
            "input": "domain-canonicalized records plus merge-review-report.json",
            "output": "kit-canonicalized.jsonl, kit-canonicalization-report.json",
            "purpose": "apply reviewed same-kit groups to every candidate while preserving aliases and evidence",
            "gate": "output count equals input count",
        },
        {
            "name": "final-selection",
            "input": "kit-canonicalized records plus merge-review-report.json",
            "output": "selected-final-records.jsonl",
            "purpose": "select target-count final records after reviewed duplicate suppression",
            "gate": "selected record count equals target count and is persisted",
        },
        {
            "name": "final-quality-gate",
            "input": "selected-final-records.jsonl",
            "output": "final-quality-report.json",
            "purpose": "verify final uniqueness, required slots, JSON safety, atomic/idempotent flags, and canonical metadata",
            "gate": "zero rejections",
        },
        {
            "name": "source-shape-audit",
            "input": "research-pack.json plus selected final records",
            "output": "source-shape-audit.json",
            "purpose": "verify final records still match source-reviewed ProtoKit/domain-kit shape",
            "gate": "public source evidence exists and every final record matches domain-first kit slots",
        },
        {
            "name": "diversity-audit",
            "input": "selected final records",
            "output": "diversity-audit.json",
            "purpose": "verify final kit breadth across domains, categories, names, and build signatures",
            "gate": "domain/category breadth and signature uniqueness thresholds pass",
        },
        {
            "name": "dependency-graph-audit",
            "input": "selected final records",
            "output": "dependency-graph-audit.json",
            "purpose": "verify requires/provides dependency graph coherence and breadth",
            "gate": "all dependency tokens are namespaced, non-empty, non-self-referential, and broad enough",
        },
        {
            "name": "build-batch-manifest",
            "input": "selected final records",
            "output": "build-batches.json",
            "purpose": "split final kits into deterministic bounded build batches for staged downstream workers",
            "gate": "all final records assigned exactly once and every batch stays within size limit",
        },
        {
            "name": "build-batch-replay-smoke",
            "input": "build-batches.json plus selected final records",
            "output": "build-batch-replay-smoke.json",
            "purpose": "prove every bounded build batch can be reconstructed from final records independently",
            "gate": "all batches replay, all listed records exist, and required slots are present",
        },
        {
            "name": "build-work-orders",
            "input": "build-batches.json plus final-kits.jsonl path",
            "output": "build-work-orders.jsonl, build-work-orders-report.json",
            "purpose": "emit one bounded downstream work order per build batch",
            "gate": "one work order per batch, unique work order ids, and full record coverage",
        },
        {
            "name": "build-batch-packets",
            "input": "build-work-orders.jsonl plus selected final records",
            "output": "build-inputs/<batch-id>/kit-records.jsonl, work-order.json, packet-report.json",
            "purpose": "materialize each work order into an isolated downstream build input folder",
            "gate": "one packet per work order, all records materialized, zero malformed packet JSONL",
        },
        {
            "name": "build-batch-dry-run",
            "input": "build-inputs/<batch-id>/kit-records.jsonl",
            "output": "batch-results/<batch-id>/build-report.json, build-batch-dry-run-report.json",
            "purpose": "process each isolated packet through a deterministic batch builder dry run",
            "gate": "one result per packet, all packet records checked, zero failed batches",
        },
        {
            "name": "build-promotion-index",
            "input": "build-batches.json plus build input packets plus dry-run reports",
            "output": "build-promotion-index.json",
            "purpose": "publish a ready/blocked queue for downstream batch promotion workers",
            "gate": "all batches ready, zero blocked batches, full record coverage",
        },
        {
            "name": "promoted-batches",
            "input": "build-promotion-index.json",
            "output": "promoted-batches/<batch-id>/promotion-report.json, promoted-batches-report.json",
            "purpose": "materialize promotion-ready batches into final downstream promotion reports",
            "gate": "all ready batches promoted, zero blocked promotions, full record coverage",
        },
        {
            "name": "downstream-build-chain-integrity",
            "input": "final-kits.jsonl plus build batch, work order, packet, dry-run, promotion, and promoted artifacts",
            "output": "downstream-build-chain-integrity.json",
            "purpose": "prove downstream build artifacts cover the same final record ids exactly once through every handoff",
            "gate": "batch ids, record ids, packet JSONL files, dry-run results, and promotion reports align",
        },
        {
            "name": "final-bucket-reconciliation",
            "input": "final-kits.jsonl plus final bucket shards",
            "output": "final-bucket-reconciliation.json",
            "purpose": "prove the sharded final bucket contains exactly the same record ids as final-kits.jsonl",
            "gate": "zero malformed records, zero duplicate ids, zero missing or extra bucket ids",
        },
        {
            "name": "feed-forward-artifact-integrity",
            "input": "all feed-forward JSONL stage artifacts",
            "output": "feed-forward-artifact-integrity.json",
            "purpose": "verify persisted stage artifacts are present, parseable, and count-aligned with report state",
            "gate": "all JSONL artifacts exist, have zero malformed lines, and match expected stage counts",
        },
        {
            "name": "stage-contract-integrity",
            "input": "manifest.json plus stage-contracts.json",
            "output": "stage-contract-integrity.json",
            "purpose": "verify manifest stage graph, stage-contract artifact, and code stage contracts agree",
            "gate": "manifest, artifact, and code stage names match exactly with complete contract fields",
        },
        {
            "name": "final-lineage-integrity",
            "input": "idea-matrix.jsonl through final-kits.jsonl",
            "output": "final-lineage-integrity.json",
            "purpose": "prove final records descend from persisted feed-forward artifacts and preserve reviewed references",
            "gate": "final ids match selected ids, exist in upstream artifacts, and referenced canonical ids exist",
        },
        {
            "name": "merge-review-coverage",
            "input": "domain and kit merge reports plus final records",
            "output": "merge-review-coverage.json",
            "purpose": "prove recursive Y/N merge reviews ran cleanly and final records carry canonical merge metadata",
            "gate": "domain and kit reviews have clean Y/N outputs, valid depths, and final canonical metadata",
        },
        {
            "name": "prompt-control-indirection",
            "input": "manifest.json plus persisted generation prompts and router controls",
            "output": "prompt-control-indirection.json",
            "purpose": "prove generation stays indirect while provider controls and temperature schedule remain enforced",
            "gate": "no final-target terms in generation prompts, 100 context tokens, 128 predictions, high-to-low temperatures",
        },
        {
            "name": "slot-decision-trace-integrity",
            "input": "lfm-slot-decisions.json plus simulator-slot-smoke.json plus sampled final records",
            "output": "slot-decision-trace-integrity.json",
            "purpose": "prove sampled LFM slot decision traces cover required slots and agree with simulator slot smoke",
            "gate": "all sampled records have one Y node per required slot, bounded prompts, and simulator agreement",
        },
        {
            "name": "stage-resume-plan",
            "input": "stage contracts, manifest stage graph, and completed run artifacts",
            "output": "stage-resume-plan.json",
            "purpose": "publish deterministic resume entries for every artifact-backed feed-forward stage",
            "gate": "every contract has resume artifacts or explicit deferred-final status with controls preserved",
        },
        {
            "name": "artifact-schema-index",
            "input": "all major JSON and JSONL run artifacts",
            "output": "artifact-schema-index.json",
            "purpose": "publish compact schema summaries for feed-forward, validation, downstream, and handoff artifacts",
            "gate": "all indexed artifacts exist, parse, and expose required top-level or payload fields",
        },
        {
            "name": "handoff-manifest",
            "input": "all final run artifacts",
            "output": "handoff-manifest.json",
            "purpose": "publish a compact start-here map for downstream builders and future agents",
            "gate": "required artifact pointers exist, controls are preserved, and batch counts align",
        },
        {
            "name": "lfm-slot-decision-tree",
            "input": "selected final records",
            "output": "lfm-slot-decisions.json",
            "purpose": "use low-temperature Y/N slot gates over sampled final records",
            "gate": "all sampled records accepted",
        },
        {
            "name": "simulator-slot-smoke",
            "input": "selected final records",
            "output": "simulator-slot-smoke.json",
            "purpose": "run simplified NexusSimulator reset, step loop, snapshot, report validation",
            "gate": "all simulated records accepted",
        },
        {
            "name": "final-output",
            "input": "all prior artifacts plus selected final records",
            "output": "final-kits.jsonl, final bucket shards, stage-ledger.json, report.json, report.md",
            "purpose": "write final JSONL, ingest into final sharded bucket, and assemble run report",
            "gate": "target JSONL lines, zero malformed records, zero failed ingests",
        },
    ]


def stage_names() -> List[str]:
    return [contract["name"] for contract in stage_contracts()]
